#Requires AutoHotkey v2.0
#SingleInstance Force

macroing := false
mainHotkey := "F12"

ai := true
model := "gpt-oss:20b-cloud"

timeBetweenTypeSegments := 0
timeBetweenSearches := 0

typoChance := 4
commaChance := 80

maxTimeBetweenTypeSegments := 125
minTimeBetweenTypeSegments := 100

maxTimeBetweenSearches := 5250
minTimeBetweenSearches := 4750

timeBeforeClear := 2000
timeBeforeSearching := 250

aiPrompt := "Gernerate an short (less than 10 words) random question someone would ask a web browser that is not related to the weather, life, any capital city, or broswing history. Do not use capital letters. Respond with only the question."
aiModels := ["gpt-oss:20b-cloud", "gemini-3-flash-preview:cloud", "deepseek-v3.1:671b-cloud", "nemotron-3-nano:30b-cloud", "ministral-3:3b-cloud", "qwen3-next:80b-cloud", "rnj-1:8b-cloud"]

guiSettingsUD := [
    {name: "Max Type Delay", var: maxTimeBetweenTypeSegments, max: 250, min: 0, x: "x10", y:"y10"},
    {name: "Min Type Delay", var: minTimeBetweenTypeSegments, max: 250, min: 0, x: "x10", y:"y55"},
    {name: "Max Time Between Searches", var: maxTimeBetweenSearches, max: 30000, min: 0, x: "x115", y:"y10"},
    {name: "Min Time Between Searches", var: minTimeBetweenSearches, max: 30000, min: 0, x: "x115", y:"y55"},
    {name: "Chance Of Typo", var: typoChance, max: 100, min: 0, x: "x268", y:"y10"},
    {name: "Chance Of StrSplit", var: commaChance, max: 100, min: 0, x: "x268", y:"y55"},
    {name: "Time Before Clear", var: timeBeforeClear, max: 5000, min: 0, x: "x10", y:"y100"},
    {name: "Time Before Search", var: timeBeforeSearching, max: 1000, min: 0, x: "x10", y:"y145"},
]

hotkeys := ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12"]

typoMapping := Map()
typoMapping["a"] := ["s", "q", "z"]
typoMapping["b"] := ["v", "n", "g"]
typoMapping["c"] := ["x", "v", "d"]
typoMapping["d"] := ["s", "f", "e", "c"]
typoMapping["e"] := ["w", "r", "s", "d"]
typoMapping["f"] := ["d", "g", "r", "v"]
typoMapping["g"] := ["f", "h", "t", "b"]
typoMapping["h"] := ["g", "j", "y", "n"]
typoMapping["i"] := ["u", "o", "k", "j"]
typoMapping["j"] := ["h", "k", "u", "m"]
typoMapping["k"] := ["j", "l", "i", "m"]
typoMapping["l"] := ["k", "o", "p"]
typoMapping["m"] := ["n", "j", "k"]
typoMapping["n"] := ["b", "m", "h"]
typoMapping["o"] := ["i", "p", "l"]
typoMapping["p"] := ["o", "l"]
typoMapping["q"] := ["w", "a"]
typoMapping["r"] := ["e", "t", "d", "f"]
typoMapping["s"] := ["a", "d", "w", "x", "z"]
typoMapping["t"] := ["r", "y", "f", "g"]
typoMapping["u"] := ["y", "i", "h", "j"]
typoMapping["v"] := ["c", "b", "f", "g"]
typoMapping["w"] := ["q", "e", "a", "s"]
typoMapping["x"] := ["z", "c", "s", "d"]
typoMapping["y"] := ["t", "u", "g", "h"]
typoMapping["z"] := ["a", "s", "x"]
typoMapping[" "] := [""]

phraseList := [
    "how to tie shoes",
    "what time is it",
    "how to cook rice",
    "why is the sky blue",
    "how to boil eggs",
    "what is my ip address",
    "how to lose weight",
    "what is the weather today",
    "how to make coffee",
    "why do cats purr",
    "how to fix wifi",
    "what is a meme",
    "how to write an email",
    "why do dogs bark",
    "how to learn coding",
    "what is bitcoin",
    "how to clean shoes",
    "where is the nearest gas station",
    "how to bake a cake",
    "what is artificial intelligence",
    "how to take a screenshot",
    "why is water wet",
    "how to tie a tie",
    "how to reset my phone",
    "where is my car",
    "how to gain muscle",
    "what is cloud storage",
    "how to delete apps",
    "why is sleep important",
    "how to edit photos",
    "what is ram",
    "how to stop hiccups",
    "where is recycle bin",
    "how to make tea",
    "what is cpu",
    "how to grow plants",
    "why do birds sing",
    "how to send a text",
    "what is phishing",
    "how to clear cache",
    "where is control panel",
    "how to tie a knot",
    "what is vpn",
    "how to open pdf files",
    "why is internet slow",
    "how to update drivers",
    "what is html",
    "how to lock screen",
    "where is task manager",
    "how to screenshot on laptop",
    "what does lol mean",
    "how to cook pasta",
    "why do we dream",
    "how to save money",
    "what is inflation",
    "how to check credit score",
    "where is my phone",
    "how to block a number",
    "how to change password",
    "what is two factor authentication",
    "how to format usb drive",
    "why is my computer slow",
    "how to install windows",
    "what is dark mode",
    "how to turn off notifications",
    "how to record screen",
    "what is malware",
    "how to uninstall programs",
    "why does my phone overheat",
    "how to clear storage",
    "what is bluetooth",
    "how to connect headphones",
    "how to share wifi password",
    "what is gps",
    "how to enable location services",
    "how to check battery health",
    "why is my phone lagging",
    "how to free up disk space",
    "what is operating system",
    "how to update phone software",
    "how to recover deleted files",
    "what is firewall",
    "how to scan for viruses",
    "why is my app crashing",
    "how to restart computer",
    "what is screenshot shortcut",
    "how to enable dark mode",
    "how to turn on bluetooth",
    "what is cache memory",
    "how to mute notifications",
    "why does wifi disconnect",
    "how to fix microphone",
    "what is cloud backup",
    "how to reset router",
    "how to improve battery life",
    "what is incognito mode",
    "how to clear browser history",
    "why is my laptop overheating",
    "how to connect printer",
    "what is ethernet",
    "how to check internet speed",
    "how to change screen resolution",
    "what is antivirus software",
    "how to enable touchpad",
    "why is my mouse not working",
    "how to enable keyboard shortcuts",
    "what is task manager used for",
    "how to close background apps",
    "why is my storage full",
    "how to backup files",
    "what is system update",
    "how to check ram usage",
    "how to enable airplane mode",
    "what is spam email",
    "how to block spam calls",
    "why is my screen flickering",
    "how to calibrate battery",
    "what is screen resolution",
    "how to change default browser",
    "how to turn off autocorrect",
    "what is cloud computing",
    "how to compress files",
    "why is my download slow",
    "how to unzip files",
    "what is zip file",
    "how to check storage usage",
    "how to enable developer mode",
    "what is api",
    "how to turn off location",
    "why is my phone battery draining fast",
    "how to enable notifications",
    "what is password manager",
    "how to change wifi name",
    "how to hide apps",
    "what is two step verification",
    "how to check software version",
    "how to reset settings",
    "what is system restore",
    "how to connect to hotspot",
    "why is my phone slow",
    "how to turn on flashlight",
    "what is airplane mode",
    "how to check signal strength",
    "how to update apps",
    "what is cloud sync",
    "how to delete browser cookies",
    "why is my screen dim",
    "how to increase volume",
    "what is accessibility mode",
    "how to enable captions",
    "how to turn off vibration",
    "what is dark web",
    "how to check device storage",
    "how to enable auto update",
    "why does my phone freeze",
    "how to reset network settings",
    "what is proxy server",
    "how to enable voice typing",
    "how to change language settings",
    "what is data roaming",
    "how to turn off roaming",
    "how to enable night mode",
    "what is software license",
    "how to uninstall apps",
    "why does my phone restart",
    "how to disable background apps",
    "what is cloud storage used for",
    "how to lock apps",
    "how to change ringtone",
    "what is notification badge",
    "how to disable pop ups",
    "why is my phone hot",
    "how to clear app cache",
    "what is system tray",
    "how to enable wifi calling",
    "how to block ads",
    "what is data usage",
    "how to check data usage",
    "why does my phone crash",
    "how to enable bluetooth pairing",
    "what is safe mode",
    "how to restart phone",
    "how to turn off auto brightness",
    "what is touch id",
    "how to set up face id",
    "how to change font size",
    "what is screen mirroring",
    "how to cast phone to tv",
    "why is my phone not charging",
    "how to clean phone speaker",
    "what is fast charging",
    "how to enable power saving mode",
    "how to check phone model",
    "what is system cache",
    "how to factory reset phone",
    "how to recover password",
    "what is device manager",
    "how to enable usb debugging",
    "why is my phone unresponsive",
    "how to disable notifications",
    "what is cloud drive",
    "how to create backup",
    "how to restore backup",
    "what is two factor login",
    "how to sync contacts",
    "why is my phone screen black",
    "how to fix touch screen",
    "what is biometric authentication",
    "how to change lock screen",
    "how to disable lock screen",
    "what is system settings",
    "how to reset app preferences",
    "why does my phone vibrate randomly",
    "how to enable screen rotation",
    "what is operating system update",
    "how to update firmware",
    "how to clear recent apps",
    "what is storage management",
    "how to change app permissions",
    "why is my phone overheating",
    "how to enable do not disturb",
    "what is mobile hotspot",
    "how to share internet",
    "how to change wallpaper",
    "what is screen timeout",
    "how to increase screen timeout",
    "why does my phone lag",
    "how to enable auto rotate",
    "what is app cache",
    "how to reset all settings",
    "how to check phone warranty",
    "what is phone firmware",
    "how to update operating system",
    "how to turn off background refresh",
    "what is phone storage",
    "how to clear phone memory",
    "why does my phone drain battery",
    "how to enable battery saver",
    "what is phone reset",
    "how to power off phone",
    "how to restart safely",
    "what is phone bootloader",
    "how to check phone health",
    "how to enable dark theme",
    "what is system ui",
    "how to clear notifications",
    "why does my phone ring silently",
    "how to enable sound",
    "what is volume mixer",
    "how to adjust notification sounds",
    "what is phone vibration mode",
    "how to disable silent mode",
    "how to enable sound notifications",
    "what is app store",
    "how to download apps",
    "how to update app store",
    "what is system app",
    "how to disable system apps",
    "how to check phone updates",
    "how to remove unused apps",
    "what is phone cache",
    "how to clear phone cache",
    "how to optimize phone",
    "why is my phone slow after update",
    "how to fix phone lag",
    "what is phone performance mode",
    "how to enable performance mode",
    "how to turn off animations",
    "what is developer options",
    "how to enable developer options",
    "how to speed up phone",
    "why is my phone freezing",
    "how to reset phone completely",
    "what is phone diagnostics",
    "how to run phone diagnostics",
    "how to fix phone issues",
    "what is phone maintenance",
    "how to maintain phone",
    "how to keep phone fast",
    "what is phone optimization",
    "how to optimize phone performance",
    "how to improve phone speed",
    "why is my phone glitching",
    "how to stop phone glitches",
    "how to change email address",
    "what is my phone number",
    "how to delete an email",
    "why is my internet not working",
    "how to turn off caps lock",
    "what does idk mean",
    "how to print a document",
    "why is my printer offline",
    "how to connect bluetooth device",
    "what is a pdf file",
    "how to change time zone",
    "why is my clock wrong",
    "how to update browser",
    "what browser am i using",
    "how to enable cookies",
    "why are websites not loading",
    "how to refresh a page",
    "what is private browsing",
    "how to clear downloads",
    "why is my browser slow",
    "how to bookmark a page",
    "what does cache mean",
    "how to enable pop ups",
    "why does my screen go black",
    "how to rotate screen",
    "what is screen brightness",
    "how to increase brightness",
    "why is my keyboard not typing",
    "how to fix sticky keys",
    "what is accessibility settings",
    "how to turn on speech to text",
    "why does my phone not ring",
    "how to turn on ringer",
    "what is vibration mode",
    "how to disable vibration",
    "why is my phone stuck",
    "how to force restart phone",
    "what is airplane mode used for",
    "how to turn off airplane mode",
    "why is my data not working",
    "how to reset mobile data",
    "what is background data",
    "how to restrict background data",
    "why does my phone use so much data",
    "how to check data plan",
    "what is roaming charges",
    "how to avoid roaming fees",
    "why is my phone screen cracked",
    "how to protect phone screen",
    "what is screen protector",
    "how to clean phone screen",
    "why does my phone echo",
    "how to fix call echo",
    "what is speaker mode",
    "how to turn off speaker",
    "why is my microphone not working",
    "how to test microphone",
    "what is voice assistant",
    "how to turn off voice assistant",
    "why does my phone talk to me",
    "how to disable voice feedback",
    "what is talkback mode",
    "how to turn off talkback",
    "why is my phone zoomed in",
    "how to turn off screen zoom",
    "what is magnification feature",
    "how to disable magnification",
    "why is my phone stuck in safe mode",
    "how to exit safe mode",
    "what is phone safe mode",
    "how to check phone temperature",
    "why does my phone get hot",
    "how to cool down phone",
    "what is phone case",
    "how to choose phone case",
    "why is my phone slippery",
    "how to improve phone grip",
    "what is phone insurance",
    "how to check phone insurance",
    "why is my phone bill high",
    "how to lower phone bill",
    "what is data rollover",
    "how to enable data saver",
    "why does my phone drop calls",
    "how to improve call quality",
    "how to change profile picture",
    "what is my email password",
    "how to sign out of account",
    "why am i logged out",
    "how to stay signed in",
    "what does otp mean",
    "how to verify my account",
    "why did i get a verification code",
    "how to change username",
    "what is account recovery",
    "how to recover my account",
    "why is my account locked",
    "how to unlock my account",
    "what is two step login",
    "how to turn off two step login",
    "how to delete my account",
    "what happens if i delete my account",
    "how to create a new account",
    "why can i not sign in",
    "how to fix login issues",
    "how to download a file",
    "where do downloads go",
    "how to open downloaded files",
    "why did my download fail",
    "how to pause a download",
    "how to resume a download",
    "what is file format",
    "how to change file name",
    "how to move files",
    "where are my files saved",
    "how to create a folder",
    "how to delete a folder",
    "why can i not delete a file",
    "how to recover deleted files",
    "what is recycle bin used for",
    "how to change keyboard language",
    "why are my keys swapped",
    "how to fix keyboard layout",
    "what is caps lock",
    "how to turn off caps lock",
    "why is text typing backwards",
    "how to fix typing issues",
    "what is on screen keyboard",
    "how to enable on screen keyboard",
    "how to connect to the internet",
    "why is wifi connected but no internet",
    "how to fix network issues",
    "what is mobile data",
    "how to turn on mobile data",
    "why is my data turned off",
    "how to check signal bars",
    "what does no service mean",
    "how to take a photo",
    "why is my camera blurry",
    "how to clean camera lens",
    "what is portrait mode",
    "how to record a video",
    "why is my camera not opening",
    "how to allow camera access",
    "what is camera permission",
    "how to set an alarm",
    "why did my alarm not ring",
    "how to change alarm sound",
    "what is snooze",
    "how to turn off alarm",
    "how to set a timer",
    "what is stopwatch used for",
    "how to check current date",
    "why is my date wrong",
    "how to change date settings",
    "what is time format",
    "how to change time format",
    "how to send pictures",
    "why are my messages not sending",
    "how to resend a message",
    "what does message failed mean",
    "how to delete messages",
    "how to mute a conversation",
    "how to check voicemail",
    "why do i have missed calls",
    "how to block unknown callers",
    "what is call forwarding",
    "how to turn off call forwarding",
    "how to make a phone call",
    "why can i not hear calls",
    "how to turn on speakerphone",
    "what is voicemail greeting",
    "how to change voicemail greeting",
    "why does my call drop",
    "how to improve phone reception",
    "what does no signal mean",
    "how to take notes",
    "what is a notes app",
    "how to organize notes",
    "how to delete notes",
    "how to recover deleted notes",
    "how to check email",
    "why am i not receiving emails",
    "how to refresh email inbox",
    "what is spam folder",
    "how to mark email as spam",
    "how to unsubscribe from emails",
    "how to share photos",
    "why are my photos missing",
    "how to recover deleted photos",
    "what is photo backup",
    "how to enable photo backup",
    "how to turn off photo backup",
    "how to download music",
    "what is a music playlist",
    "how to create a playlist",
    "why is my music not playing",
    "how to connect bluetooth speaker",
    "how to watch videos",
    "why is video buffering",
    "how to change video quality",
    "what is full screen mode",
    "how to exit full screen",
    "how to use voice search",
    "why is voice search not working",
    "how to turn off voice search",
    "what is voice recognition",
    "how to search faster",
    "what is search history",
    "how to clear search history",
    "why are suggestions showing",
    "how to turn off search suggestions",
    "how to use maps",
    "why is my location wrong",
    "how to get directions",
    "how to avoid toll roads",
    "what is gps navigation",
    "how to check calendar",
    "how to add an event",
    "why is my calendar empty",
    "how to delete calendar events",
    "how to set reminders",
    "how to use calculator",
    "what is percentage calculation",
    "how to calculate tip",
    "how to convert units",
    "how to convert currency",
    "how to check news",
    "why is news not updating",
    "how to change news topics",
    "what is breaking news",
    "how to check sports scores",
    "why are live scores delayed",
    "how to follow a team",
    "what time is the game",
    "how to check traffic",
    "why is traffic heavy",
    "how to avoid traffic",
    "what is rush hour",
    "how to shop online",
    "is online shopping safe",
    "how to track an order",
    "why is my order delayed",
    "how to cancel an order",
    "how to make a payment",
    "why did my payment fail",
    "how to check payment history",
    "what is digital wallet",
    "how to add a payment method",
    "how to check bank balance",
    "why is my card declined",
    "how to reset bank password",
    "what is online banking",
    "how to book a ticket",
    "why is my booking not confirmed",
    "how to cancel a booking",
    "what is a booking reference",
    "how to check flight status",
    "why is my flight delayed",
    "how early to arrive at airport",
    "what is boarding pass",
    "how to check hotel availability",
    "how to book a hotel",
    "why was my reservation canceled",
    "what is check in time",
    "how to order food online",
    "why is my food late",
    "how to contact delivery driver",
    "what is delivery fee",
    "how to find restaurants nearby",
    "what is the best restaurant near me",
    "how to read reviews",
    "why are reviews missing",
    "how to check store hours",
    "is the store open today",
    "what time does the store close",
    "what stores are open now",
    "how to find a job",
    "what jobs are hiring near me",
    "how to write a resume",
    "how to prepare for interview",
    "how to learn faster",
    "what is online learning",
    "how to study better",
    "how to focus while studying",
    "how to relax",
    "what is stress relief",
    "how to sleep better",
    "why can i not fall asleep",
    "how to wake up early",
    "what is a sleep schedule",
    "how many hours should i sleep",
    "how to stay healthy",
    "what is a balanced diet",
    "how to start exercising",
    "how often should i exercise",
    "how to cook dinner",
    "what should i eat tonight",
    "how to meal prep",
    "what is a healthy snack",
    "how to clean house",
    "how often to clean",
    "what is the best cleaning routine",
    "how to save time",
    "how to be more productive",
    "how to stay organized",
    "what is time management",
    "how to make friends",
    "how to meet new people",
    "how to improve communication",
    "how to be confident"
]