#Requires AutoHotkey v2.0

phraseList := [
    "ho,w t,o ti,e sho,es",
    "wh,at i,s th,e ti,me",
    "ho,w t,o co,ok ri,ce",
    "wh,y i,s th,e sk,y bl,ue",
    "ho,w t,o lo,se we,ig,ht",
    "wh,at i,s m,y i,p",
    "ho,w t,o bo,il eg,gs",
    "wh,er,e i,s m,y ph,on,e",
    "ho,w t,o dr,aw a ca,t",
    "wh,at i,s 2 pl,us 2",
    "ho,w t,o sa,ve mo,ne,y",
    "wh,y d,o ca,ts pu,rr",
    "ho,w t,o fi,x wi,fi",
    "wh,at i,s a me,me",
    "ho,w t,o wr,it,e em,ai,l",
    "wh,y d,o do,gs ba,rk",
    "ho,w t,o le,ar,n co,di,ng",
    "wh,at i,s bi,tc,oi,n",
    "ho,w t,o cl,ea,n sh,oe,s",
    "wh,er,e i,s ne,ar,es,t ga,s",
    "ho,w t,o ba,ke ca,ke",
    "wh,at i,s a,i",
    "ho,w t,o sc,ree,nsh,ot pc",
    "wh,y i,s wa,te,r we,t",
    "ho,w t,o ti,e a ti,e",
    "wh,at i,s m,y pa,ss,wo,rd",
    "ho,w t,o re,se,t ph,on,e",
    "wh,er,e i,s m,y ca,r",
    "ho,w t,o ga,in mu,sc,le",
    "wh,at i,s cl,ou,d st,or,ag,e",
    "ho,w t,o de,le,te ap,ps",
    "wh,y i,s sl,ee,p im,po,rt,an,t",
    "ho,w t,o ed,it ph,ot,os",
    "wh,at i,s ra,m",
    "ho,w t,o st,op hi,cc,up,s",
    "wh,er,e i,s re,cy,cl,e bi,n",
    "ho,w t,o ma,ke co,ff,ee",
    "wh,at i,s cp,u",
    "ho,w t,o gr,ow pl,an,ts",
    "wh,y d,o bi,rd,s si,ng",
    "ho,w t,o se,nd te,xt",
    "wh,at i,s ph,is,hi,ng",
    "ho,w t,o cl,ea,r ca,che",
    "wh,er,e i,s co,nt,ro,l pa,ne,l",
    "ho,w t,o ti,e kn,ot",
    "wh,at i,s vp,n",
    "ho,w t,o op,en pd,f",
    "wh,y i,s in,te,rn,et sl,ow",
    "ho,w t,o up,da,te dr,iv,er,s",
    "wh,at i,s ht,ml",
    "ho,w t,o lo,ck sc,ree,n",
    "wh,er,e i,s ta,sk ma,na,ge,r",
    "ho,w t,o ma,ke re,su,me",
    "wh,at i,s us,b",
    "ho,w t,o ch,an,ge fo,nt",
    "wh,y d,o le,av,es fa,ll",
    "ho,w t,o sc,an do,cu,me,nt",
    "wh,at i,s fi,re,wa,ll",
    "ho,w t,o mu,te mi,c",
    "wh,er,e i,s do,wn,lo,ad,s fo,ld,er",
    "ho,w t,o zi,p fi,le,s",
    "wh,at i,s ma,lw,ar,e",
    "ho,w t,o re,co,rd sc,ree,n",
    "wh,y i,s m,y pc lo,ud",
    "ho,w t,o sh,ar,e lo,ca,ti,on",
    "wh,at i,s ap,i",
    "ho,w t,o tu,rn of,f vp,n",
    "wh,er,e i,s de,vi,ce ma,na,ge,r",
    "ho,w t,o un,in,st,al,l ap,ps",
    "wh,at i,s ra,m us,ed fo,r",
    "ho,w t,o fi,x la,g",
    "wh,y i,s ph,on,e ho,t",
    "ho,w t,o ch,an,ge pa,ss,wo,rd",
    "wh,at i,s et,he,rn,et",
    "ho,w t,o sy,nc fi,le,s",
    "wh,er,e i,s cl,ip,bo,ar,d",
    "ho,w t,o ma,ke ta,bl,e",
    "wh,at i,s jp,g",
    "ho,w t,o re,se,t ro,ut,er",
    "wh,y i,s wi,fi we,ak",
    "ho,w t,o op,en bi,os",
    "wh,at i,s gp,u",
    "ho,w t,o ch,ec,k st,or,ag,e",
    "wh,er,e i,s sy,st,em se,tt,in,gs",
    "ho,w t,o pr,in,t pd,f",
    "wh,at i,s da,rk mo,de",
    "ho,w t,o re,na,me fi,le,s",
    "wh,y i,s ba,tt,er,y dr,ai,ni,ng",
    "ho,w t,o co,py pa,st,e",
    "wh,at i,s zi,p fi,le",
    "ho,w t,o cl,ea,n ki,tch,en",
    "wh,at i,s a do,cu,me,nt",
    "ho,w t,o fo,rm,at pc",
    "wh,er,e i,s th,e ne,ar,es,t ca,fe",
    "ho,w t,o se,ar,ch we,b",
    "wh,at i,s a lo,an",
    "ho,w t,o se,nd em,ai,l",
    "wh,y d,o pl,an,ts gr,ow",
    "ho,w t,o ch,ec,k bl,oo,d pr,es,sur,e",
    "wh,at i,s a pr,oj,ec,t",
    "ho,w t,o bo,ok fl,ig,hts",
    "wh,er,e i,s th,e ba,nk",
    "ho,w t,o se,nd mo,ne,y on,lin,e",
    "wh,at i,s a he,al,th ap,p",
    "ho,w t,o ge,t st,ar,te,d wi,th co,di,ng",
    "wh,y i,s so,ci,al me,di,a po,pu,la,r",
    "ho,w t,o fi,x ph,on,e sc,re,en",
    "wh,at i,s a di,gi,ta,l wa,ll,et",
    "ho,w t,o pr,ep,ar,e su,pp,ers",
    "wh,er,e i,s th,e cl,os,et",
    "ho,w t,o le,ar,n mu,si,c",
    "wh,at i,s a vo,ic,e as,si,st,an,t",
    "ho,w t,o or,ga,niz,e do,cum,ent,s",
    "wh,y d,o we ha,ve da,ys an,d ni,gh,ts",
    "ho,w t,o ch,ec,k ve,hic,le in,fo",
    "wh,at i,s a pl,an ne,t",
    "ho,w t,o pr,ep,ar,e re,po,rt,s",
    "wh,er,e i,s th,e po,st,of,fi,ce",
    "ho,w t,o ch,an,ge la,ng,ua,ge se,tt,in,gs",
    "wh,at i,s a br,ow,ser ex,ten,sion",
    "ho,w t,o cr,eat,e bl,og po,st,s",
    "wh,y d,o bi,rd,s mi,gr,at,e",
    "ho,w t,o le,ar,n fo,re,ig,n la,ng,ua,ge",
    "wh,at i,s a vi,de,o co,de,r",
    "ho,w t,o do w,or,k ou,t",
    "wh,er,e i,s th,e ne,ar,es,t su,pe,rma,r,ke,t",
    "ho,w t,o wr,it,e co,ve,r le,tt,er,s",
    "wh,at i,s a sc,he,du,le",
    "ho,w t,o se,ar,ch fo,r jo,b s",
    "wh,y i,s th,e we,at,he,r ch,an,gi,ng",
    "ho,w t,o st,ay fo,cu,se,d",
    "wh,at i,s a ga,me st,re,am,er",
    "ho,w t,o cr,eat,e su,mm,ar,y",
    "wh,er,e i,s th,e ne,ar,es,t ga,s st,at,io,n",
    "ho,w t,o le,ar,n pi,an,o",
    "wh,at i,s a fo,od al,er,t",
    "ho,w t,o re,co,rd vo,ic,e no,te,s",
    "wh,y d,o we ta,ke va,ca,ti,ons",
    "ho,w t,o se,nd po,st ca,rd,s",
    "wh,at i,s a su,bs,cr,ip,ti,on",
    "ho,w t,o or,ga,niz,e ph,ot,os",
    "wh,er,e i,s th,e ne,ar,es,t ho,sp,it,al",
    "ho,w t,o ch,ec,k ba,nk ba,la,nc,e",
    "wh,at i,s a da,sh,bo,ar,d",
    "ho,w t,o le,ar,n dr,aw,in,g",
    "wh,y d,o fo,od sp,oi,l",
    "ho,w t,o fi,x re,fr,ig,er,at,or",
    "wh,at i,s a co,ur,ie,r se,rv,ic,e",
    "ho,w t,o bu,il,d a ca,bi,ne,t",
    "wh,er,e i,s th,e ne,ar,es,t po,ol",
    "ho,w t,o le,ar,n ph,ot,og,ra,ph,y",
    "wh,at i,s a da,ta ba,se",
    "ho,w t,o ch,ec,k ve,hic,le re,g,ist,ra,ti,on",
    "wh,y i,s so,il i,mp,or,ta,nt",
    "ho,w t,o ma,ke ch,oc,ol,at,e",
    "wh,at i,s a br,oa,dca,st",
    "ho,w t,o se,nd in,vi,ta,ti,ons",
    "wh,er,e i,s th,e ne,ar,es,t li,br,ar,y",
    "ho,w t,o re,ad ne,ws on,li,ne",
    "wh,at i,s a so,ci,al me,di,a ac,co,un,t",
    "ho,w t,o do la,un,dr,y",
    "wh,y d,o pl,an,ts ne,ed su,nli,gh,t",
    "ho,w t,o bu,il,d a sl,id,e sh,ow",
    "wh,at i,s a vi,de,o fo,r ma,t",
    "ho,w t,o se,nd te,xt me,ss,ag,e",
    "wh,er,e i,s th,e ne,ar,es,t st,or,e",
    "ho,w t,o ch,ec,k em,ai,l ac,co,un,t",
    "wh,at i,s a mo,bi,le ap,p",
    "ho,w t,o do ma,th pr,ob,le,ms",
    "wh,y i,s wa,te,r im,po,rt,an,t",
    "ho,w t,o bu,il,d a fi,re,pi,t",
    "wh,at i,s a da,sh,bo,ar,d we,bs,it,e",
    "ho,w t,o co,mp,ar,e pr,ic,es",
    "wh,er,e i,s th,e ne,ar,es,t ca,mp,si,te",
    "ho,w t,o le,ar,n si,ng,in,g",
    "wh,at i,s a po,dca,st",
    "ho,w t,o do ga,rd,en,in,g",
    "wh,y d,o le,av,es ch,an,ge co,lo,r",
    "ho,w t,o se,nd pa,ck,ag,e",
    "wh,at i,s a ch,at bo,t",
    "ho,w t,o wr,it,e a bl,og",
    "wh,er,e i,s th,e ne,ar,es,t re,st,au,ra,nt",
    "ho,w t,o le,ar,n ma,th",
    "wh,at i,s a di,gi,ta,l cl,oc,k",
    "ho,w t,o do ex,er,ci,se",
    "wh,y d,o st,ar,s tw,ink,le",
    "ho,w t,o bu,il,d a sh,el,f",
    "wh,at i,s a vi,de,o st,re,am",
    "ho,w t,o se,nd em,ai,l at,ta,ch,me,nt",
    "wh,er,e i,s th,e ne,ar,es,t li,gh,th,ou,se",
    "ho,w t,o le,ar,n gi,ta,r",
    "wh,at i,s a no,ti,fic,at,io,n",
    "ho,w t,o do sk,et,ch,in,g",
    "wh,y d,o cl,ou,ds fo,rm",
    "ho,w t,o ma,ke sa,la,d",
    "wh,at i,s a cr,yp,to cu,rr,en,cy",
    "ho,w t,o se,nd te,xt m,es,sa,ge",
    "wh,er,e i,s th,e ne,ar,es,t su,pe,rm,ar,ke,t",
    "ho,w t,o wr,it,e re,vi,ew",
    "wh,at i,s a po,li,cy",
    "ho,w t,o do ex,pe,ri,me,nt",
    "wh,y d,o fo,od ca,rm,el,ize",
    "ho,w t,o bu,il,d a ta,bl,e",
    "wh,at i,s a ch,ar,ge,rs",
    "ho,w t,o se,nd vi,de,o",
    "wh,er,e i,s th,e ne,ar,es,t te,ac,he,r",
    "ho,w t,o le,ar,n pi,an,o so,ng",
    "wh,at i,s a te,xt bo,ok",
    "ho,w t,o do st,ud,y se,ss,io,n",
    "wh,y d,o we sl,ee,p",
    "ho,w t,o ma,ke sm,oo,th,ie",
    "wh,at i,s a da,ta pl,an",
    "ho,w t,o se,nd in,vi,ta,ti,ons vi,a em,ai,l",
    "wh,er,e i,s th,e ne,ar,es,t ga,rd,en",
    "ho,w t,o wr,it,e a no,te",
    "wh,at i,s a br,ow,se,r ho,ok",
    "ho,w t,o le,ar,n to sw,im",
    "wh,y d,o w,e br,ea,th,e",
    "ho,w t,o bu,il,d a fo,od st,an,d",
    "wh,at i,s a ve,hi,cl,e re,pa,ir",
    "ho,w t,o do pl,ay ba,sk,et,ba,ll",
    "wh,er,e i,s th,e ne,ar,es,t co,ff,ee sh,op",
    "ho,w t,o ch,ec,k ba,gg,ag,e st,at,us",
    "wh,at i,s a ba,si,c co,mp,ut,er",
    "ho,w t,o se,nd in,vi,ta,ti,ons on,li,ne",
    "wh,y d,o ri,ve,rs fl,ow",
    "ho,w t,o wr,it,e a sc,ri,pt",
    "wh,at i,s a ne,ws le,tt,er",
    "ho,w t,o do ga,me de,ve,lo,pm,en,t",
    "wh,er,e i,s th,e ne,ar,es,t ba,th,ro,om",
    "ho,w t,o le,ar,n fo,od re,ci,pe",
    "wh,at i,s a br,ow,se,r ex,te,ns,io,n",
    "ho,w t,o do mu,lt,ipl,e ch,oi,ce te,st",
    "wh,y d,o pl,an,ts fl,ow,er",
    "ho,w t,o bu,il,d a ga,rd,en be,d",
    "wh,at i,s a da,ta ba,se ma,na,ge,me,nt",
    "ho,w t,o se,nd do,cu,me,nt",
    "wh,er,e i,s th,e ne,ar,es,t po,li,ce st,at,io,n",
    "ho,w t,o wr,it,e a le,tt,er",
    "wh,at i,s a no,ti,fic,at,io,n ce,nt,er",
    "ho,w t,o le,ar,n ph,ot,og,ra,ph,y ba,sic,s",
    "wh,y d,o le,av,es tu,rn ye,ll,ow",
    "ho,w t,o do da,nc,e le,ss,ons",
    "wh,at i,s a te,xt bo,x",
    "ho,w t,o bu,il,d a sh,el,f fo,r bo,ok,s",
    "wh,er,e i,s th,e ne,ar,es,t bu,s st,op",
    "ho,w t,o ch,ec,k w,eat,he,r fo,re,ca,st",
    "wh,at i,s a br,ow,se,r se,ar,ch en,gi,ne",
    "ho,w t,o se,nd pa,ck,ag,e vi,a po,st",
    "wh,y d,o ri,ve,rs fl,oo,d",
    "ho,w t,o wr,it,e a da,ta re,po,rt",
    "wh,at i,s a mo,bi,le da,ta pl,an",
    "ho,w t,o do ex,er,ci,se ro,ut,in,e",
    "wh,er,e i,s th,e ne,ar,es,t re,st,au,ra,nt",
    "ho,w t,o le,ar,n gi,ta,r so,ngs",
    "wh,at i,s a co,mp,ut,er ga,me",
    "ho,w t,o bu,il,d a te,nt",
    "wh,y d,o cl,ou,ds fo,rm ra,in",
    "ho,w t,o se,nd a vi,de,o me,ss,ag,e",
    "wh,at i,s a pr,oj,ec,t ma,na,ge,me,nt to,ol",
    "ho,w t,o wr,it,e a re,po,rt",
    "wh,er,e i,s th,e ne,ar,es,t ph,ar,ma,cy",
    "ho,w t,o ch,ec,k ba,nk ac,co,un,t ba,la,nc,e",
    "wh,at i,s a do,cu,me,nt sc,an,ne,r",
    "ho,w t,o le,ar,n to dr,aw pe,op,le",
    "wh,y d,o st,ar,s tw,ink,le",
    "ho,w t,o bu,il,d a ba,rg,ai,n li,st",
    "wh,at i,s a br,ow,se,r hi,sto,ry",
    "ho,w t,o se,nd a te,xt me,ss,ag,e",
    "wh,er,e i,s th,e ne,ar,es,t li,br,ar,y",
    "ho,w t,o wr,it,e a no,te",
    "wh,at i,s a da,ta ba,se co,de",
    "ho,w t,o do pl,ay gu,ita,r",
    "wh,y d,o we sl,ee,p",
    "ho,w t,o ma,ke sm,oo,th,ie",
    "wh,at i,s a cl,ou,d st,or,ag,e se,rv,ic,e",
    "ho,w t,o se,nd in,vi,ta,ti,ons vi,a em,ai,l",
    "wh,er,e i,s th,e ne,ar,es,t su,pe,rm,ar,ke,t",
    "ho,w t,o wr,it,e re,vi,ew",
    "wh,at i,s a po,li,cy",
    "ho,w t,o do ex,pe,ri,me,nt",
    "wh,y d,o fo,od ca,rm,el,ize",
    "ho,w t,o bu,il,d a ta,bl,e",
    "wh,at i,s a ch,ar,ge,rs",
    "ho,w t,o se,nd vi,de,o",
    "wh,er,e i,s th,e ne,ar,es,t te,ac,he,r",
    "ho,w t,o le,ar,n pi,an,o so,ng",
    "wh,at i,s a te,xt bo,ok",
    "ho,w t,o do st,ud,y se,ss,io,n",
    "wh,y d,o we sl,ee,p",
    "ho,w t,o ma,ke sm,oo,th,ie",
    "wh,at i,s a da,ta pl,an",
    "ho,w t,o se,nd in,vi,ta,ti,ons vi,a em,ai,l",
    "wh,er,e i,s th,e ne,ar,es,t ga,rd,en",
    "ho,w t,o wr,it,e a no,te",
    "wh,at i,s a br,ow,se,r ho,ok",
    "ho,w t,o le,ar,n to sw,im",
    "wh,y d,o w,e br,ea,th,e",
    "ho,w t,o bu,il,d a fo,od st,an,d",
    "wh,at i,s a ve,hi,cl,e re,pa,ir",
    "ho,w t,o do pl,ay ba,sk,et,ba,ll",
    "wh,er,e i,s th,e ne,ar,es,t co,ff,ee sh,op",
    "ho,w t,o ch,ec,k ba,gg,ag,e st,at,us",
    "wh,at i,s a ba,si,c co,mp,ut,er",
    "ho,w t,o se,nd in,vi,ta,ti,ons on,li,ne",
    "wh,y d,o ri,ve,rs fl,ow",
    "ho,w t,o wr,it,e a sc,ri,pt",
    "wh,at i,s a ne,ws le,tt,er",
    "ho,w t,o do ga,me de,ve,lo,pm,en,t",
    "wh,er,e i,s th,e ne,ar,es,t ba,th,ro,om",
    "ho,w t,o le,ar,n fo,od re,ci,pe",
    "wh,at i,s a br,ow,se,r ex,te,ns,io,n",
    "ho,w t,o do mu,lt,ipl,e ch,oi,ce te,st",
    "wh,y d,o pl,an,ts fl,ow,er",
    "ho,w t,o bu,il,d a ga,rd,en be,d",
    "wh,at i,s a da,ta ba,se ma,na,ge,me,nt",
    "ho,w t,o se,nd do,cu,me,nt",
    "wh,er,e i,s th,e ne,ar,es,t po,li,ce st,at,io,n",
    "ho,w t,o wr,it,e a le,tt,er",
    "wh,at i,s a no,ti,fic,at,io,n ce,nt,er",
    "ho,w t,o le,ar,n ph,ot,og,ra,ph,y ba,sic,s",
    "wh,y d,o le,av,es tu,rn ye,ll,ow",
    "ho,w t,o do da,nc,e le,ss,ons",
    "wh,at i,s a te,xt bo,x",
    "ho,w t,o bu,il,d a sh,el,f fo,r bo,ok,s",
    "wh,er,e i,s th,e ne,ar,es,t bu,s st,op",
    "ho,w t,o ch,ec,k w,eat,he,r fo,re,ca,st",
    "wh,at i,s a br,ow,se,r se,ar,ch en,gi,ne",
    "ho,w t,o se,nd pa,ck,ag,e vi,a po,st",
    "wh,y d,o ri,ve,rs fl,oo,d",
    "ho,w t,o wr,it,e a da,ta re,po,rt",
    "wh,at i,s a mo,bi,le da,ta pl,an",
    "ho,w t,o do ex,er,ci,se ro,ut,in,e",
    "wh,er,e i,s th,e ne,ar,es,t re,st,au,ra,nt",
    "ho,w t,o le,ar,n gi,ta,r so,ngs",
    "wh,at i,s a co,mp,ut,er ga,me",
    "ho,w t,o bu,il,d a te,nt",
    "wh,y d,o cl,ou,ds fo,rm ra,in",
    "ho,w t,o se,nd a vi,de,o me,ss,ag,e",
    "wh,at i,s a pr,oj,ec,t ma,na,ge,me,nt to,ol",
    "ho,w t,o wr,it,e a re,po,rt",
    "wh,er,e i,s th,e ne,ar,es,t ph,ar,ma,cy",
    "ho,w t,o ch,ec,k ba,nk ac,co,un,t ba,la,nc,e",
    "wh,at i,s a do,cu,me,nt sc,an,ne,r",
    "ho,w t,o le,ar,n to dr,aw pe,op,le",
    "wh,y d,o st,ar,s tw,ink,le",
    "ho,w t,o bu,il,d a ba,rg,ai,n li,st",
    "wh,at i,s a br,ow,se,r hi,sto,ry",
    "ho,w t,o se,nd a te,xt me,ss,ag,e",
    "wh,er,e i,s th,e ne,ar,es,t li,br,ar,y",
    "ho,w t,o wr,it,e a no,te",
    "wh,at i,s a da,ta ba,se co,de",
    "ho,w t,o do pl,ay gu,ita,r",
    "wh,y d,o we sl,ee,p",
    "ho,w t,o ma,ke sm,oo,th,ie",
    "wh,at i,s a cl,ou,d st,or,ag,e se,rv,ic,e",
    "ho,w t,o se,nd in,vi,ta,ti,ons vi,a em,ai,l",
    "wh,er,e i,s th,e ne,ar,es,t su,pe,rm,ar,ke,t",
    "ho,w t,o wr,it,e re,vi,ew",
    "wh,at i,s a po,li,cy",
    "ho,w t,o do ex,pe,ri,me,nt",
    "wh,y d,o fo,od ca,rm,el,ize",
    "ho,w t,o bu,il,d a ta,bl,e",
    "wh,at i,s a ch,ar,ge,rs",
    "ho,w t,o se,nd vi,de,o",
    "wh,er,e i,s th,e ne,ar,es,t te,ac,he,r",
    "ho,w t,o le,ar,n pi,an,o so,ng",
    "wh,at i,s a te,xt bo,ok",
    "ho,w t,o do st,ud,y se,ss,io,n",
    "wh,y d,o we sl,ee,p",
    "ho,w t,o ma,ke sm,oo,th,ie",
    "wh,at i,s a da,ta pl,an",
    "ho,w t,o se,nd in,vi,ta,ti,ons vi,a em,ai,l",
    "wh,er,e i,s th,e ne,ar,es,t ga,rd,en",
    "ho,w t,o wr,it,e a no,te",
    "wh,at i,s a br,ow,se,r ho,ok",
    "ho,w t,o le,ar,n to sw,im",
    "wh,y d,o w,e br,ea,th,e",
    "ho,w t,o bu,il,d a fo,od st,an,d",
    "wh,at i,s a ve,hi,cl,e re,pa,ir",
    "ho,w t,o do pl,ay ba,sk,et,ba,ll",
    "wh,er,e i,s th,e ne,ar,es,t co,ff,ee sh,op",
    "ho,w t,o ch,ec,k ba,gg,ag,e st,at,us",
    "wh,at i,s a ba,si,c co,mp,ut,er",
    "ho,w t,o se,nd in,vi,ta,ti,ons on,li,ne",
    "wh,y d,o ri,ve,rs fl,ow",
    "ho,w t,o wr,it,e a sc,ri,pt",
    "wh,at i,s a ne,ws le,tt,er",
    "ho,w t,o do ga,me de,ve,lo,pm,en,t",
    "wh,er,e i,s th,e ne,ar,es,t ba,th,ro,om",
    "ho,w t,o le,ar,n fo,od re,ci,pe",
    "wh,at i,s a br,ow,se,r ex,te,ns,io,n",
    "ho,w t,o do mu,lt,ipl,e ch,oi,ce te,st",
    "wh,y d,o pl,an,ts fl,ow,er",
    "ho,w t,o bu,il,d a ga,rd,en be,d",
    "wh,at i,s a da,ta ba,se ma,na,ge,me,nt",
    "ho,w t,o se,nd do,cu,me,nt",
    "wh,er,e i,s th,e ne,ar,es,t po,li,ce st,at,io,n",
    "ho,w t,o wr,it,e a le,tt,er",
    "wh,at i,s a no,ti,fic,at,io,n ce,nt,er",
    "ho,w t,o le,ar,n ph,ot,og,ra,ph,y ba,sic,s",
    "wh,y d,o le,av,es tu,rn ye,ll,ow",
    "ho,w t,o do da,nc,e le,ss,ons",
    "wh,at i,s a te,xt bo,x",
    "ho,w t,o bu,il,d a sh,el,f fo,r bo,ok,s",
    "wh,er,e i,s th,e ne,ar,es,t bu,s st,op",
    "ho,w t,o ch,ec,k w,eat,he,r fo,re,ca,st",
    "wh,at i,s a br,ow,se,r se,ar,ch en,gi,ne"
]
